[package]
name = "mate_solver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
once_cell = "1"
shogi_legality_lite = "0.1.1"
shogi_core = "0.1.4"
rand = "0.9"
rand_chacha = "0.9"

[dev-dependencies]
shogi_usi_parser = "0.1"
