name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  RUSTDOCFLAGS: --deny warnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo version
      run: cargo --version
    - name: install nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --locked --all --all-features
    - name: Run clippy
      run: cargo clippy --all-targets --locked --all
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Document
      run: cargo doc --verbose
